[build-system]
requires = [
    "setuptools>=61",
    "wheel",
    "setuptools_scm[toml]"
]
build-backend = "setuptools.build_meta"

[project]
    ######
    #temporary project name with "idaes-ui-test", when package please rename this with the final name!
    ######
    name = "idaes-ui-test"
    description = "IDAES Process Systems Engineering User Interface"
    readme = "README.md"
    version = "0.0.5"
    license = {text="BSD"}
    requires-python = ">=3.8"
    authors = [
        {name="The IDAES Project"},
        {name="Dan Gunter", email="dkgunter@lbl.gov"}
    ]
    classifiers = [
            "Development Status :: 3 - Alpha",
            "Intended Audience :: End Users/Desktop",
            "Intended Audience :: Science/Research",
            "License :: OSI Approved :: BSD License",
            "Natural Language :: English",
            "Operating System :: MacOS",
            "Operating System :: Microsoft :: Windows",
            "Operating System :: Unix",
            "Programming Language :: Python",
            "Programming Language :: Python :: 3",
            "Programming Language :: Python :: 3.8",
            "Programming Language :: Python :: 3.9",
            "Programming Language :: Python :: 3.10",
            "Programming Language :: Python :: 3.11",
            "Programming Language :: Python :: Implementation :: CPython",
            "Topic :: Scientific/Engineering :: Mathematics",
            "Topic :: Scientific/Engineering :: Chemistry",
            "Topic :: Software Development :: Libraries :: Python Modules",
    ]
    dependencies = [
        # Don't version setuptools, various bits complain
        "setuptools",
        # For running tests
        "pytest",
        # IDAES release
        "idaes-pse >= 2.0.0",
        # dependency 'requests' module for standalone idaes-ui package
        "requests",
    ]
    keywords = ["IDAES", "energy systems", "chemical engineering", "process modeling"]

[project.optional-dependencies]
# Just for developers (they should also add 'jb')
dev = [
    # For adding copyright headers (see addheader.yml and the readme)
    "addheader >= 0.3.0",
    # Get IDAES from main branch in Github
    #"idaes-pse @ git+https://github.com/IDAES/idaes-pse"
    # For PyPI enable this (Sheng)
    "idaes-pse >= 2.0.0"
]
# For packaging
pkg = [
    "build",
    "twine"
]

[project.urls]
github = "https://github.com/idaes/idaes-ui"
issues = "https://github.com/idaes/idaes-ui/issues"

[project.scripts]
# idaesx = "idaes_examples.build:main"

# testing script for executeable script after pip install (Sheng)
idaes-ui-example = "idaes_ui.fv.example:main"

[tool.setuptools]
include-package-data = true
zip-safe = false

[tool.setuptools.packages]
find = {namespaces = false}

[tool.setuptools.package-data]
idaes_ui = [
    "*.template",
    "*.json",
    "*.yaml",
    "*.svg",
    "*.png",
    "*.jpg",
    "*.csv",
    "*.ipynb",
    "*.txt",
    "*.js",
    "*.css",
    "*.html",
    "*.json.gz",
    "*.dat",
    "*.yml",
    "*.yaml",
    "fv/static/lib/**/*"
]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra"
testpaths = [
    "idaes_ui"
]

markers = [
    "component: between unit and integration test",
    "unit: test one small unit of functionality",
    "integration: test integrated functionality"
]